<?php
/**
 * This template displays the Product Category and Tag taxonomy term archives
 *
 * @package genesis_connect_woocommerce
 * @version 0.9.5
 *
 * Note for customisers/users: Do not edit this file!
 * ==================================================
 * If you want to customise this template, copy this file (keep same name) and place the
 * copy in the child theme's woocommerce folder, ie themes/my-child-theme/woocommerce
 * (Your theme may not have a 'woocommerce' folder, in which case create one.)
 * The version in the child theme's woocommerce folder will override this template, and
 * any future updates to this plugin won't wipe out your customisations.
 *
 */


// Remove default Genesis loop
remove_action( 'genesis_loop', 'genesis_do_loop' );

// Remove WooCommerce breadcrumbs
remove_action( 'woocommerce_before_main_content', 'woocommerce_breadcrumb', 20 );

// Remove Woo #container and #content divs
remove_action( 'woocommerce_before_main_content', 'woocommerce_output_content_wrapper', 10 );
remove_action( 'woocommerce_after_main_content', 'woocommerce_output_content_wrapper_end', 10 );

// Add the WooCommerce content
add_action( 'genesis_before_loop', array( Genesis_WooCommerce()->templates, 'woo_content' ) );

genesis();
