version: 2.1

orbs:
  wp-svn: studiopress/wp-svn@0.2

jobs:
  checks:
    docker:
      - image: cimg/php:7.3-node
    steps:
      - checkout
      - run: composer i && composer phpcs

workflows:
  test-deploy:
    jobs:
      - checks
      - approval-for-deploy-tested-up-to-bump:
          type: approval
          requires:
            - checks
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^bump-tested-up-to.*/
      - wp-svn/deploy-tested-up-to-bump:
          requires:
            - approval-for-deploy-tested-up-to-bump

  tag_deploy:
    jobs:
      - checks:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              only: /.*/
      - wp-svn/deploy:
          dry-run: true
          requires:
            - checks
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              only: /.*/
