version: 2.1

orbs:
  wp-svn: studiopress/wp-svn@0.2

jobs:
  lint:
    docker:
      - image: cimg/php:7.3-node
    steps:
      - checkout
      - run: composer i && composer phpcs

workflows:
  test-deploy:
    jobs:
      - lint
      - approval-for-deploy-tested-up-to-bump:
          type: approval
          requires:
            - lint
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^bump-tested-up-to.*/
      - wp-svn/deploy-tested-up-to-bump:
          context: genesis-svn
          requires:
            - approval-for-deploy-tested-up-to-bump

  tag-deploy:
    jobs:
      - lint:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - wp-svn/deploy:
          context: genesis-svn
          requires:
            - lint
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
